// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu3PHIrCTbYzyAesEWK9HEyDIXooIy6lg',
    appId: '1:1065631766562:web:052a0473dadda2fa20d27b',
    messagingSenderId: '1065631766562',
    projectId: 'chat-app-f9b74',
    authDomain: 'chat-app-f9b74.firebaseapp.com',
    storageBucket: 'chat-app-f9b74.firebasestorage.app',
    measurementId: 'G-QTHVSVM5Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrG637HrodZCk9DEtmuAtgBcUWoZagrA',
    appId: '1:1065631766562:android:698f0be2e3b2b92220d27b',
    messagingSenderId: '1065631766562',
    projectId: 'chat-app-f9b74',
    storageBucket: 'chat-app-f9b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTzFU4Avb5g-v7_1iEYOSlCr6-c6-1Eo',
    appId: '1:1065631766562:ios:406c4e95ed6d571020d27b',
    messagingSenderId: '1065631766562',
    projectId: 'chat-app-f9b74',
    storageBucket: 'chat-app-f9b74.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTzFU4Avb5g-v7_1iEYOSlCr6-c6-1Eo',
    appId: '1:1065631766562:ios:406c4e95ed6d571020d27b',
    messagingSenderId: '1065631766562',
    projectId: 'chat-app-f9b74',
    storageBucket: 'chat-app-f9b74.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu3PHIrCTbYzyAesEWK9HEyDIXooIy6lg',
    appId: '1:1065631766562:web:fda231396cff199620d27b',
    messagingSenderId: '1065631766562',
    projectId: 'chat-app-f9b74',
    authDomain: 'chat-app-f9b74.firebaseapp.com',
    storageBucket: 'chat-app-f9b74.firebasestorage.app',
    measurementId: 'G-SB3ERLDFFD',
  );
}
